##title: "Finding the best deal among Central European hotels"
##Take necessary packages in library
library(tidyverse)
library(modelsummary)
library(dplyr)
library(knitr)
library(ggthemes)

##clean the environment
rm(list=ls())

##Import data online
df <- read.csv('https://osf.io/yzntm/download')

glimpse(df)

###Questions###
#1. Clean the data and give a short overview
#2. Summarize the main variables and plot their graphs
#3. Find the correlation between price and distance
#4. Find the correlation between guest reviewing report with distance and price
#5. Test whether there is no statistical significant difference in the price of hotels between year 2017 and 2018
#6. There is no statistical significant difference in the price of hotels between summer and winter season
#7. Test whether there is any statistical significant difference in the review report of on the basis of starrating
.

###1. Clean the data and give a short overview

## Some value are non-zero but include zeros. The next table checks the zero values and the quantity of unique values.

kable(funModeling::df_status(df))

##The folowing manipulations were carried out on the original data to change the existing variables and to add new ones:
#The type of the variables *center1distance* and *guestreviewsrating* were changed from 'string' to 'numeric'. The new variable names are *distance* *distance2* and *actualrating * respectively.

# guestreviewrating separation

df <- separate(df, guestreviewsrating, ' /', into =
                 c('actualrating', 'rate'))
df <- select(df, -rate)
df$actualrating <- as.numeric(df$actualrating)


# Distance from city center 1
df <- separate(df, center1distance, ' ', into =
                 c('distance', 'miles')) 
df <- select(df, -miles)
df$distance <- as.numeric(df$distance)


# Distance from city center 2
df <- separate(df, center2distance, ' ', into =
                 c('distance2', 'miles')) 
df <- select(df, -miles)
df$distance2 <- as.numeric(df$distance2)

# country as factor variable
df$country <- as.factor(df$addresscountryname)
df <- select(df, -addresscountryname)

#The original *accommodationtype* variable was tranformed into new *acctype_f* factor variable.

df <- separate(df, accommodationtype, '@', into = 
                 c('word', 'acctype'))
df <- select(df, -word)
df <- mutate(df, acctype_f = factor(acctype))

#*trueprice* variable was generated by dividing the original *price* variable by *price_night*


df <- separate(df, price_night, ' ', into =
                 c('pr','word', 'nights', 'night'))
df <- select(df, -pr)
df <- select(df, -night)
df <- select(df, -word)
df$nights <- as.numeric(df$nights)
df$trueprice <- df$price/df$nights

#*season* variable was created based on the *month* variable

df <- df %>%
  mutate(season = case_when(month == 12 | month == 1 |month == 2 ~ 'winter',
                            month == 3 | month == 4 |month == 5 ~ 'spring',
                            month == 6 | month == 7 |month == 8 ~ 'summer',
                            month == 9 | month == 10 |month == 11 ~ 'autumn'))
df$season <- as.factor(df$season)


## Filtering Dataset for 7 Central European countries
##For our analysis we used 7 Central European countries: Czech Republic, Germany, Italy, Hungary, Austria, Poland, Slovakia.

df2 <- df %>% filter(country %in% c('Czech Republic', 'Germany',
                                    'Italy','Hungary','Austria','Poland','Slovakia')) %>%
  filter(s_city %in% c('Prague', 'Budapest', 'Berlin', 'Rome', 'Budapest', 'Vienna', 'Warsaw', 'Bratislava'), city_actual %in%
           c('Prague', 'Budapest', 'Berlin', 'Rome', 'Budapest', 'Vienna', 'Warsaw', 'Bratislava')) %>% 
  filter(acctype == 'Hotel', starrating >= 2 & starrating < 4) %>% 
  filter(season== 'summer'| season== 'winter')%>% 
  filter(year=='2017'| year== '2018') %>% 
  filter(trueprice <= 150, distance<=8)


##Overview of the variables

variables <- c('hotel_id','acctype', 'country', 's_city', 'weekend', 'holiday',
               'distance', 'distance2', 'starrating', 'actualrating', 'trueprice','season',
               'year')
info <- c('Hotel ID', 'Type of accomodation', 'Country', 'Name of the Capital', 'Flag, if day is a weekend',
          'Flag, if day is a public holiday', 'Distance from main city center','Distance from second city center',
          'Number of stars', 'User rating average', 'Price in EUR', 'Name of season according to month',
          'Year (YYYY)')
type <- c('numeric', 'string', 'string', 'string','binary', 'binary', 'numeric','numeric','numeric',
          'numeric', 'numeric', 'string', 'numeric')

description <- data.frame(variables, info, type)

kable(description, caption = "Description of the main variables in the original dataset")

### • Quality of the dataset - missing values overview and frequency distribution of numeric values

df2 %>% 
  skimr::skim_without_charts() 

#2. Summarize the main variables and plot their graphs
## Summary for the main variables in the transformed dataset *Numeric variables*

Range = function(x)
  max(x, na.rm = T) - min(x, na.rm = T)

Quantile = function(x)
  quantile(x, na.rm= T, probs = c(.5, .95))

datasummary(distance + starrating + actualrating + trueprice ~ Mean + Min + Max + SD+ Range+ Quantile, data = df2) %>%
  kableExtra::kable_styling(latex_options = "hold_position")


##Distance

f1 <- ggplot(data = df2) +
  geom_density(aes(x = distance), color = 'purple', fill = 'white' , bw = 0.5) +
  labs(x = 'Distance from City Center',
       y = 'Relative Frequency')

f1 <- f1+ geom_histogram(aes( y = ..density.., x = distance), color = 'orange', fill= 'grey',
                                         alpha = 0.4, binwidth = 0.5)
f1



f2 <-ggplot(df2, aes(x = s_city, y = distance,
                            color = s_city))+
  stat_summary_bin(fun = 'mean', bins = 7, 
                   geom = 'point',  size = 2) +
  labs(x = 'City', y = 'Distance from city cente', 
       color = 'navyblue')+
  facet_wrap(~s_city, scales = 'free', nrow = 2)+
  theme(legend.position = 'none')+
  geom_smooth(method='lm',formula = y~x, se=F)

f2


## trueprice

f3 <- ggplot(data = df2) +
  geom_histogram(aes(x = trueprice), color = 'navyblue', fill= 'grey',
                 bins = 10) +
  labs(x = 'Perce per night for hotel rent',
       y = 'Count')
y_value <- 50
m_price <- df2 %>%summarise(mean=mean(trueprice, na.rm=TRUE))
print(m_price)

f3 <- f3+ geom_segment(aes(x=m_price$mean, y=0,
                           xend=m_price$mean, yend=y_value),
                       color='red')
f3 


f4 <- ggplot(data = df2) + 
  geom_point(mapping = aes(x = s_city, color = s_city, y = trueprice))+
  labs(x = 'Cities',
       y = 'Hotel price per night')+
  facet_wrap(~s_city, scales = 'free', nrow = 2)
f4


### • Starrating

f5 <- ggplot(df2, aes(y=actualrating, x=s_city))+
  geom_boxplot()+
  labs(x='Cities', y='Ratings of Hotel')
f5 


##Actualrating

f6 <- ggplot(df2, aes(y=actualrating, x=s_city))+
  geom_violin()+
  labs(x='Cities', y='Guest Review ratings')
f6 

###3. Find the correlation between truelprice and distance 
corr_table1 <- df2 %>% 
  select(country, trueprice, distance) %>% 
  group_by(country) %>% 
  summarise(correlation = cor(trueprice,distance))

corr_table1

# Graph to show the correlation pattern by each country:

ggplot(corr_table1, aes(x = correlation ,
                       y = fct_reorder(country, correlation))) +
  geom_point(color = 'red', size = 2)+
  labs(y='Countries',x='Correlation')

###4. Find the correlation between guest reviewing report with distance and price
corr_table2 <- cor(df2[, c('trueprice','actualrating','distance')])

###5. Is there any statistical significant difference in the hotel price per night between year 2017 and 2018
t.test(df2$trueprice [df2$year=="2017"],df2$trueprice [df2$year=="2018"], mu=0, alt='two.sided', conf=0.95, paired=F)
#Null Hypothesis is rejected though the t-statistic is insignificant 

###6. There is no statistical significant difference in the price of hotels between summer and winter season
t.test(df2$trueprice [df2$season=="winter"],df2$trueprice [df2$season=="summer"], mu=0, alt='two.sided', conf=0.95, paired=F)
#Null Hypothesis is rejected 

#5. Test the hypothesize that there is no statistical significant difference between guest reviewing report as per the starrating
 
df2 <- df2 %>% mutate(newrating = ifelse(starrating< 1, 'tourist','comfort'))

t.test(df2$actualrating [df2$newrating=="tourist"],df2$actualrating [df2$newrating=="comfort"], paired=T)

#Null Hypothesis is rejected 